//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrdID { get; set; }
        public Nullable<int> CusID { get; set; }
        public Nullable<int> PrID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> SaID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Products Products { get; set; }
        public virtual Sales Sales { get; set; }
    }
}
