//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int PrID { get; set; }
        public string ProductName { get; set; }
        public string PrDescription { get; set; }
        public Nullable<int> Price { get; set; }
        public string ProductImage { get; set; }
    }
}
